### ISSUE TITLE
Test Day 5 Code

### ISSUE THREAD

**Issue by alessasystem** [jaydeslibrary/crimson_love#4]
Leaving this to remind you!

**Comment by jaydeslibrary** [comment]
I'm doing it... stfu...

**Comment by alessasystem** [comment]
Hmph.

**Comment by jaydeslibrary** [comment]
![image](https://user-images.githubusercontent.com/129603537/233456076-c80854e0-3033-40c1-9a0f-f79fb5225e78.png)

**Comment by jaydeslibrary** [comment]
![image](https://user-images.githubusercontent.com/129603537/233456182-4902a0ce-41e0-441f-bb9e-992ce10c40e8.png)

**Comment by jaydeslibrary** [comment]
I fixed it.

**Comment by jaydeslibrary** [comment]
[lint.txt](https://github.com/jaydeslibrary/crimson_love/files/11289385/lint.txt)
Adding a placeholder label to fix this.

**Comment by jaydeslibrary** [comment]
Route 1 works!

**Comment by jaydeslibrary** [comment]
Both days work. I'm gonna do a bit of script editing.
